##values-dev.yaml
environment: dev  # or prod for values-prod.yaml

frontend:
  image:
    repository: bansikah/shop-frontend
    tag: "1.2.0"
  replicaCount: 1
  env:
    REACT_APP_API_URL: "http://shop-app-dev.local/api"
  ports:
    - containerPort: 80

backend:
  image:
    repository: bansikah/shop-backend
    tag: "1.2.0"
  replicaCount: 1

postgres:
  image:
    repository: postgres
    tag: latest
  database: shopdb
  username: postgresuser
  password: postgrespass  

ingress:
  host: shop-app-dev.local  