apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | b64enc }}